version: "3.9"

services:
  codex_manager:
    container_name: "codex_manager"
    image: ghcr.io/martokk/codex_manager:latest
    restart: unless-stopped
    volumes:
      # - /home/ubuntu/volumes/codex_manager/data:/codex_manager/data
      - ./app:/app
    ports:
      - "5000:5000"
