version: "3.9"

services:
  python_fastapi_stack:
    container_name: "python_fastapi_stack"
    image: "python_fastapi_stack"
    build:
      context: .
      # context: https://github.com/martokk/python_fastapi_stack.git#main
      target: production
    restart: unless-stopped
    # depends_on:
    #   - duckdns
    env_file:
      # - /home/ubuntu/volumes/python_fastapi_stack/.env
      - ./python_fastapi_stack/.env
    volumes:
      # - /home/ubuntu/volumes/python_fastapi_stack/.env:/workspace/.env
      # - /home/ubuntu/volumes/python_fastapi_stack/media:/workspace/media
      # - /home/ubuntu/volumes/python_fastapi_stack/logs:/workspace/logs
      # - /home/ubuntu/volumes/python_fastapi_stack/db.sqlite3:/workspace/db.sqlite3
      - ./python_fastapi_stack:/python_fastapi_stack
    ports:
      - "5000:5000"
