"""update

Revision ID: 28eb5adea630
Revises: 5962a73ec8f2
Create Date: 2024-08-01 10:56:55.127409

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '28eb5adea630'
down_revision = '5962a73ec8f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_year_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_year_start', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('old_year_end', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('new_year_end', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('new_year_end')
        batch_op.drop_column('old_year_end')
        batch_op.drop_column('new_year_start')
        batch_op.drop_column('old_year_start')

    # ### end Alembic commands ###
