"""init

Revision ID: c3550b7c0e9d
Revises: 816d7d05a7c9
Create Date: 2024-07-18 15:24:27.518416

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c3550b7c0e9d'
down_revision = '816d7d05a7c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
