"""init

Revision ID: d6835423c512
Revises: fc7bd577f29f
Create Date: 2024-07-17 13:28:22.872925

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd6835423c512'
down_revision = 'fc7bd577f29f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
