"""init

Revision ID: fc7bd577f29f
Revises: b10ff0670be4
Create Date: 2024-07-17 13:26:00.224304

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'fc7bd577f29f'
down_revision = 'b10ff0670be4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
